import { FullProfileConfig } from "@/types/profile";

export const DEFAULT_PROFILE_CONFIG: FullProfileConfig = {
  username: "koni",
  bio: "premium profile developer & designer @ alternate.lol",
  card: {
    layout: "floating-card",
    width: 480,
    height: "auto",
    scale: 1,
    rotationX: 0,
    rotationY: 0,
    padding: 24,
    margin: 16,
    borderRadius: 24,
    opacity: 1,
    glassBlur: 16,
    backgroundOpacity: 0.25,
    dropShadow: true,
    glowStrength: 10,
    glowColor: "#ff007f",
    outlineThickness: 1.5,
    outlineColor: "#ffffff40",
    borderStyle: "solid",
    borderEffect: "animated-gradient",
    backgroundNoise: true,
    backgroundGrain: true,
    floatingEffect: true,
  },
  background: {
    type: "animated-gradient",
    color1: "#09090b",
    color2: "#180828",
    color3: "#020617",
    imageUrl: "",
    videoUrl: "",
    brightness: 100,
    saturation: 100,
    contrast: 100,
    blur: 0,
    opacity: 1,
    overlayColor: "#000000",
    overlayOpacity: 0.4,
  },
  particles: {
    type: "stars",
    density: 80,
    speed: 0.6,
    opacity: 0.8,
    color: "#ffffff",
    size: 2,
    spawnRate: 5,
    gravity: 0,
    wind: 0,
    mouseInteraction: true,
    clickInteraction: true,
  },
  typography: {
    fontFamily: "Geist Sans",
    fontWeight: "500",
    usernameColor: "#ffffff",
    bioColor: "#94a3b8",
    subtitleColor: "#38bdf8",
    descriptionOpacity: 0.85,
    textGlow: true,
    textShadow: true,
    textEffect: "gradient",
    textGradientColor1: "#ff007f",
    textGradientColor2: "#7c3aed",
  },
  cursor: {
    type: "animated",
    customUrl: "",
    size: 20,
    glow: true,
    glowColor: "#ff007f",
    trail: "sparkles",
    dampening: 5,
  },
  splash: {
    enabled: true,
    text: "alternate.lol",
    subtitle: "[ click to enter ]",
    buttonText: "Proceed to Profile",
    backgroundColor: "#030014e6",
    glassBlur: 20,
    fadeSpeed: 0.8,
    enterSoundUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    pulseEffect: true,
  },
  mediaPlayer: {
    enabled: true,
    autoplay: false,
    loop: true,
    volume: 50,
    backgroundColor: "#0c0a0f",
    backgroundOpacity: 0.4,
    glassBlur: 12,
    progressColor: "#ff007f",
    textColor: "#ffffff",
    borderRadius: 16,
    glowStrength: 8,
    position: "inside-card",
    currentTrackIndex: 0,
    trackList: [
      {
        id: "1",
        url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
        title: "Sunset Chords",
        artist: "Lofi Beats",
        coverUrl: "https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=150&auto=format&fit=crop&q=60",
        lyrics: "[00:00] (Instrumental Intro)\n[00:15] Chill lofi beats playing in the evening sunset...\n[00:30] Feeling relaxed and calm\n[00:45] The lights are glowing dim\n[01:00] Beautiful glassmorphism effects all around\n[01:30] Enjoying alternate.lol private linker page",
      },
      {
        id: "2",
        url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
        title: "Retro Dreams",
        artist: "Synthwave Collector",
        coverUrl: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=150&auto=format&fit=crop&q=60",
        lyrics: "[00:00] (Synth chords fading in)\n[00:20] Dreaming in retro grids\n[00:40] Cyberpunk vibes in the digital rain\n[01:00] Running fast on the highway",
      }
    ],
  },
  discord: {
    enabled: true,
    userId: "123456789012345678",
    mockStatus: {
      username: "koni683",
      displayName: "koni",
      avatarUrl: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=60",
      bannerUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=60",
      accentColor: "#7c3aed",
      status: "dnd",
      customStatus: "coding alternate.lol... 💻",
      activityName: "Visual Studio Code",
      activityDetails: "Editing page.tsx - alternate.lol project",
      spotifySong: "Sunset Chords",
      spotifyArtist: "Lofi Beats",
      spotifyAlbumUrl: "https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=150&auto=format&fit=crop&q=60",
      badges: ["staff", "nitro", "booster"],
    },
  },
  links: [
    { id: "1", platform: "Discord", url: "https://discord.gg/zuka", glow: true, glowColor: "#5865F2", animation: "pulse", iconColor: "#5865F2", visible: true },
    { id: "2", platform: "YouTube", url: "https://www.youtube.com/@koni683", glow: false, glowColor: "#FF0000", animation: "none", iconColor: "#FF0000", visible: true },
    { id: "3", platform: "TikTok", url: "https://www.tiktok.com/@67fovkoni", glow: true, glowColor: "#00f2fe", animation: "bounce", iconColor: "#00f2fe", visible: true },
    { id: "4", platform: "GitHub", url: "https://github.com", glow: false, glowColor: "#ffffff", animation: "none", iconColor: "#ffffff", visible: true },
    { id: "5", platform: "Spotify", url: "https://spotify.com", glow: false, glowColor: "#1DB954", animation: "none", iconColor: "#1DB954", visible: true }
  ],
  badges: [
    { id: "owner", name: "Owner", icon: "Crown", tooltip: "Platform Owner", glow: true, glowColor: "#fbbf24", animation: "float", color: "#fbbf24", visible: true },
    { id: "dev", name: "Developer", icon: "Code", tooltip: "Core Developer", glow: true, glowColor: "#3b82f6", animation: "pulse", color: "#3b82f6", visible: true },
    { id: "staff", name: "Staff", icon: "Shield", tooltip: "Official Staff Member", glow: false, glowColor: "#10b981", animation: "none", color: "#10b981", visible: true },
    { id: "premium", name: "Premium", icon: "Gem", tooltip: "Premium Lifetime Subscriber", glow: true, glowColor: "#ec4899", animation: "pulse", color: "#ec4899", visible: true },
    { id: "alpha", name: "Alpha", icon: "Flame", tooltip: "Alpha Tester", glow: false, glowColor: "#f97316", animation: "none", color: "#f97316", visible: true },
    { id: "verified", name: "Verified", icon: "CheckCircle", tooltip: "Verified Account", glow: true, glowColor: "#3b82f6", animation: "none", color: "#3b82f6", visible: true }
  ],
  widgets: [
    { id: "1", type: "views", title: "Views", value: 14322, visible: true, x: 0, y: 0 },
    { id: "2", type: "likes", title: "Likes", value: 1205, visible: true, x: 0, y: 0 },
    { id: "3", type: "online", title: "Status", value: "Online", visible: true, x: 0, y: 0 }
  ]
};

export const PRESET_THEMES: Record<string, Partial<FullProfileConfig>> = {
  "neon-pink": {
    card: {
      layout: "floating-card",
      width: 480,
      height: "auto",
      scale: 1,
      rotationX: 0,
      rotationY: 0,
      padding: 24,
      margin: 16,
      borderRadius: 24,
      opacity: 1,
      glassBlur: 16,
      backgroundOpacity: 0.2,
      dropShadow: true,
      glowStrength: 15,
      glowColor: "#ec4899",
      outlineThickness: 1.5,
      outlineColor: "#ec4899aa",
      borderStyle: "solid",
      borderEffect: "glow",
      backgroundNoise: true,
      backgroundGrain: false,
      floatingEffect: true,
    },
    background: {
      type: "animated-gradient",
      color1: "#090514",
      color2: "#1c0018",
      color3: "#020108",
      imageUrl: "",
      videoUrl: "",
      brightness: 100,
      saturation: 120,
      contrast: 100,
      blur: 0,
      opacity: 1,
      overlayColor: "#000000",
      overlayOpacity: 0.3,
    },
    particles: {
      type: "sparkles",
      density: 60,
      speed: 1,
      opacity: 0.9,
      color: "#ec4899",
      size: 3,
      spawnRate: 4,
      gravity: 0,
      wind: 0,
      mouseInteraction: true,
      clickInteraction: true,
    }
  },
  "cyberpunk": {
    card: {
      layout: "floating-card",
      width: 480,
      height: "auto",
      scale: 1,
      rotationX: 0,
      rotationY: 0,
      padding: 24,
      margin: 16,
      borderRadius: 4,
      opacity: 1,
      glassBlur: 12,
      backgroundOpacity: 0.3,
      dropShadow: true,
      glowStrength: 12,
      glowColor: "#eab308",
      outlineThickness: 2,
      outlineColor: "#06b6d4",
      borderStyle: "solid",
      borderEffect: "rgb-rainbow",
      backgroundNoise: true,
      backgroundGrain: true,
      floatingEffect: false,
    },
    background: {
      type: "animated-gradient",
      color1: "#0c0e12",
      color2: "#1e1b4b",
      color3: "#020617",
      imageUrl: "",
      videoUrl: "",
      brightness: 100,
      saturation: 130,
      contrast: 110,
      blur: 0,
      opacity: 1,
      overlayColor: "#000000",
      overlayOpacity: 0.5,
    },
    particles: {
      type: "matrix",
      density: 50,
      speed: 1.5,
      opacity: 0.7,
      color: "#00ff66",
      size: 12,
      spawnRate: 2,
      gravity: 0.2,
      wind: 0,
      mouseInteraction: false,
      clickInteraction: false,
    }
  },
  "minimal-frost": {
    card: {
      layout: "floating-card",
      width: 460,
      height: "auto",
      scale: 1,
      rotationX: 0,
      rotationY: 0,
      padding: 28,
      margin: 12,
      borderRadius: 32,
      opacity: 1,
      glassBlur: 25,
      backgroundOpacity: 0.1,
      dropShadow: false,
      glowStrength: 0,
      glowColor: "#ffffff",
      outlineThickness: 1,
      outlineColor: "#ffffff22",
      borderStyle: "solid",
      borderEffect: "none",
      backgroundNoise: false,
      backgroundGrain: false,
      floatingEffect: true,
    },
    background: {
      type: "solid",
      color1: "#0f172a",
      color2: "#0f172a",
      color3: "#0f172a",
      imageUrl: "",
      videoUrl: "",
      brightness: 100,
      saturation: 100,
      contrast: 100,
      blur: 0,
      opacity: 1,
      overlayColor: "#000000",
      overlayOpacity: 0,
    },
    particles: {
      type: "snow",
      density: 40,
      speed: 0.5,
      opacity: 0.6,
      color: "#ffffff",
      size: 2.5,
      spawnRate: 1,
      gravity: 0.05,
      wind: 0.02,
      mouseInteraction: true,
      clickInteraction: false,
    }
  }
};
