import { FullProfileConfig } from "@/types/profile";

export const DEFAULT_PROFILE_CONFIG: FullProfileConfig = {
  username: "koni",
  bio: "premium profile developer & designer @ alternate.lol",
  card: {
    layout: "floating-card",
    width: 480,
    height: "auto",
    scale: 1,
    rotationX: 0,
    rotationY: 0,
    padding: 24,
    margin: 16,
    borderRadius: 16,
    opacity: 1,
    glassBlur: 12,
    backgroundOpacity: 0.35,
    dropShadow: true,
    glowStrength: 0,
    glowColor: "#ffffff",
    outlineThickness: 1,
    outlineColor: "#ffffff1a",
    borderStyle: "solid",
    borderEffect: "none",
    backgroundNoise: true,
    backgroundGrain: true,
    floatingEffect: true,
  },
  background: {
    type: "solid",
    color1: "#09090b",
    color2: "#09090b",
    color3: "#09090b",
    imageUrl: "",
    videoUrl: "",
    brightness: 100,
    saturation: 100,
    contrast: 100,
    blur: 0,
    opacity: 1,
    overlayColor: "#000000",
    overlayOpacity: 0.5,
  },
  particles: {
    type: "stars",
    density: 40,
    speed: 0.2,
    opacity: 0.5,
    color: "#ffffff",
    size: 1.5,
    spawnRate: 2,
    gravity: 0,
    wind: 0,
    mouseInteraction: true,
    clickInteraction: false,
  },
  typography: {
    fontFamily: "Geist Sans",
    fontWeight: "400",
    usernameColor: "#ffffff",
    bioColor: "#a1a1aa",
    subtitleColor: "#71717a",
    descriptionOpacity: 0.9,
    textGlow: false,
    textShadow: false,
    textEffect: "none",
    textGradientColor1: "#ffffff",
    textGradientColor2: "#a1a1aa",
  },
  cursor: {
    type: "default",
    customUrl: "",
    size: 20,
    glow: false,
    glowColor: "#ffffff",
    trail: "none",
    dampening: 5,
  },
  splash: {
    enabled: true,
    text: "alternate.lol",
    subtitle: "[ click to enter ]",
    buttonText: "Proceed to Profile",
    backgroundColor: "#09090be6",
    glassBlur: 12,
    fadeSpeed: 0.6,
    enterSoundUrl: "",
    pulseEffect: false,
  },
  mediaPlayer: {
    enabled: true,
    autoplay: false,
    loop: true,
    volume: 50,
    backgroundColor: "#09090b",
    backgroundOpacity: 0.6,
    glassBlur: 12,
    progressColor: "#ffffff",
    textColor: "#ffffff",
    borderRadius: 12,
    glowStrength: 0,
    position: "inside-card",
    currentTrackIndex: 0,
    trackList: [
      {
        id: "1",
        url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
        title: "Sunset Chords",
        artist: "Lofi Beats",
        coverUrl: "https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=150&auto=format&fit=crop&q=60",
        lyrics: "[00:00] (Instrumental Intro)",
      }
    ],
  },
  discord: {
    enabled: true,
    userId: "123456789012345678",
    mockStatus: {
      username: "koni683",
      displayName: "koni",
      avatarUrl: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=60",
      bannerUrl: "",
      accentColor: "#18181b",
      status: "dnd",
      customStatus: "coding alternate.lol...",
      activityName: "Visual Studio Code",
      activityDetails: "alternate.lol design revamp",
      spotifySong: "Sunset Chords",
      spotifyArtist: "Lofi Beats",
      spotifyAlbumUrl: "https://images.unsplash.com/photo-1614613535308-eb5fbd3d2c17?w=150&auto=format&fit=crop&q=60",
      badges: ["staff"],
    },
  },
  links: [
    { id: "1", platform: "Discord", url: "https://discord.gg/zuka", glow: false, glowColor: "#ffffff", animation: "none", iconColor: "#ffffff", visible: true },
    { id: "2", platform: "YouTube", url: "https://www.youtube.com/@koni683", glow: false, glowColor: "#ffffff", animation: "none", iconColor: "#ffffff", visible: true },
    { id: "3", platform: "TikTok", url: "https://www.tiktok.com/@67fovkoni", glow: false, glowColor: "#ffffff", animation: "none", iconColor: "#ffffff", visible: true },
    { id: "4", platform: "GitHub", url: "https://github.com", glow: false, glowColor: "#ffffff", animation: "none", iconColor: "#ffffff", visible: true }
  ],
  badges: [
    { id: "owner", name: "Owner", icon: "Crown", tooltip: "Platform Owner", glow: false, glowColor: "#ffffff", animation: "none", color: "#ffffff", visible: true },
    { id: "dev", name: "Developer", icon: "Code", tooltip: "Core Developer", glow: false, glowColor: "#ffffff", animation: "none", color: "#ffffff", visible: true },
    { id: "staff", name: "Staff", icon: "Shield", tooltip: "Official Staff Member", glow: false, glowColor: "#ffffff", animation: "none", color: "#ffffff", visible: true }
  ],
  widgets: [
    { id: "1", type: "views", title: "Views", value: 14322, visible: true, x: 0, y: 0 }
  ]
};

export const PRESET_THEMES: Record<string, Partial<FullProfileConfig>> = {
  "neon-pink": {
    card: {
      layout: "floating-card",
      width: 480,
      height: "auto",
      scale: 1,
      rotationX: 0,
      rotationY: 0,
      padding: 24,
      margin: 16,
      borderRadius: 24,
      opacity: 1,
      glassBlur: 16,
      backgroundOpacity: 0.2,
      dropShadow: true,
      glowStrength: 15,
      glowColor: "#ec4899",
      outlineThickness: 1.5,
      outlineColor: "#ec4899aa",
      borderStyle: "solid",
      borderEffect: "glow",
      backgroundNoise: true,
      backgroundGrain: false,
      floatingEffect: true,
    },
    background: {
      type: "animated-gradient",
      color1: "#090514",
      color2: "#1c0018",
      color3: "#020108",
      imageUrl: "",
      videoUrl: "",
      brightness: 100,
      saturation: 120,
      contrast: 100,
      blur: 0,
      opacity: 1,
      overlayColor: "#000000",
      overlayOpacity: 0.3,
    },
    particles: {
      type: "sparkles",
      density: 60,
      speed: 1,
      opacity: 0.9,
      color: "#ec4899",
      size: 3,
      spawnRate: 4,
      gravity: 0,
      wind: 0,
      mouseInteraction: true,
      clickInteraction: true,
    }
  },
  "cyberpunk": {
    card: {
      layout: "floating-card",
      width: 480,
      height: "auto",
      scale: 1,
      rotationX: 0,
      rotationY: 0,
      padding: 24,
      margin: 16,
      borderRadius: 4,
      opacity: 1,
      glassBlur: 12,
      backgroundOpacity: 0.3,
      dropShadow: true,
      glowStrength: 12,
      glowColor: "#eab308",
      outlineThickness: 2,
      outlineColor: "#06b6d4",
      borderStyle: "solid",
      borderEffect: "rgb-rainbow",
      backgroundNoise: true,
      backgroundGrain: true,
      floatingEffect: false,
    },
    background: {
      type: "animated-gradient",
      color1: "#0c0e12",
      color2: "#1e1b4b",
      color3: "#020617",
      imageUrl: "",
      videoUrl: "",
      brightness: 100,
      saturation: 130,
      contrast: 110,
      blur: 0,
      opacity: 1,
      overlayColor: "#000000",
      overlayOpacity: 0.5,
    },
    particles: {
      type: "matrix",
      density: 50,
      speed: 1.5,
      opacity: 0.7,
      color: "#00ff66",
      size: 12,
      spawnRate: 2,
      gravity: 0.2,
      wind: 0,
      mouseInteraction: false,
      clickInteraction: false,
    }
  },
  "minimal-frost": {
    card: {
      layout: "floating-card",
      width: 460,
      height: "auto",
      scale: 1,
      rotationX: 0,
      rotationY: 0,
      padding: 28,
      margin: 12,
      borderRadius: 32,
      opacity: 1,
      glassBlur: 25,
      backgroundOpacity: 0.1,
      dropShadow: false,
      glowStrength: 0,
      glowColor: "#ffffff",
      outlineThickness: 1,
      outlineColor: "#ffffff22",
      borderStyle: "solid",
      borderEffect: "none",
      backgroundNoise: false,
      backgroundGrain: false,
      floatingEffect: true,
    },
    background: {
      type: "solid",
      color1: "#0f172a",
      color2: "#0f172a",
      color3: "#0f172a",
      imageUrl: "",
      videoUrl: "",
      brightness: 100,
      saturation: 100,
      contrast: 100,
      blur: 0,
      opacity: 1,
      overlayColor: "#000000",
      overlayOpacity: 0,
    },
    particles: {
      type: "snow",
      density: 40,
      speed: 0.5,
      opacity: 0.6,
      color: "#ffffff",
      size: 2.5,
      spawnRate: 1,
      gravity: 0.05,
      wind: 0.02,
      mouseInteraction: true,
      clickInteraction: false,
    }
  }
};
